let cardData = [
  {
    cardName: "A La Carte",
    cardValue: 20,
    cardImg:
      "https://caasco.com/-/media/caasco/membership/cards/435x274/membership_card_AlaCarte.jpg",
    cardLink: {
      url: "tel:1-877-475-5061",
      label: "Call 1-877-475-5061",
    },
    selectValue: "aLaCarte",
    bestValue: false,
    rvOption: "",
    roadside: ["—", "—", "—", "—", "—", "—", "—"],
    savings: [
      "Member pricing on Canadian passport photos",
      "Member pricing on merchandise online with shopwithcaa.com and in CAA Stores<sup>4</sup>",
      "Save instantly at any of the 124,000 participating retail locations in North America. You can save on apparel, restaurants, the latest tech, entertainment and more",
      "Save or get perks on travel, including car rentals, hotel stays, vacation packages and more",
    ],
    benefits: [
      "Unlimited general practitioner consults per year at a 20% discounted rate with Maple",
      "—",
      "—",
      "—",
    ],
  },
  {
    cardName: "Basic",
    cardValue: 75,
    cardImg:
      "https://www.caasco.com/~/media/caasco/membership/cards/membership_card_Basic.png",
    cardLink: {
      url: "https://www.caasco.com/membership/Join?Type=Basic",
      label: "Join Now",
    },
    selectValue: "basic",
    bestValue: false,
    rvOption: "",
    roadside: [
      "Four service calls",
      "Towing distance of 10 km per call<sup>1</sup>",
      "Free emergency fuel delivery.Fuel costs extra.",
      "Mobile battery service<sup>2</sup>",
      "Member pricing on CAA Premium Battery purchase<sup>2</sup>",
      "CAA Bike Assist<sup>&trade;</sup><sup>3</sup>",
      "Car and bike coverage",
    ],
    savings: [
      "Member pricing on Canadian passport photos",
      "Member pricing on merchandise online with shopwithcaa.com and in CAA Stores<sup>4</sup>",
      "Save instantly at any of the 124,000 participating retail locations in North America. You can save on apparel, restaurants, the latest tech, entertainment and more",
      "Save or get perks on travel, including car rentals, hotel stays, vacation packages and more",
    ],
    benefits: [
      "Unlimited general practitioner consults per year at a 20% discounted rate with Maple",
      "Road Trip Accident Assistance<sup>5</sup>",
      "—",
      "—",
    ],
  },
  {
    cardName: "Plus",
    cardValue: 119,
    cardImg:
      "https://www.caasco.com/~/media/caasco/membership/cards/membership_card_Plus.png",
    cardLink: {
      url: "https://www.caasco.com/membership/Join?Type=Basic",
      label: "Join Now",
    },
    selectValue: "plus",
    bestValue: true,
    rvOption:"RV option for $67/year more",
    roadside: [
      "Four service calls",
      "Towing distance of 200 km per call<sup>1</sup>",
      "Free emergency fuel and delivery.",
      "Mobile battery service<sup>2</sup>",
      "Member pricing on CAA Premium Battery purchase<sup>2</sup>",
      "CAA Bike Assist<sup>&trade;</sup><sup>3</sup>",
      "Car, bike and motorcycle coverage",
    ],
    savings: [
      "Free Canadian passport photos",
      "Additional 5% off Member pricing on merchandise online with shopwithcaa.com and in CAA Stores<sup>4</sup>",
      "Save instantly at any of the 124,000 participating retail locations in North America. You can save on apparel, restaurants, the latest tech, entertainment and more",
      "Save or get perks on travel, including car rentals, hotel stays, vacation packages and more",
    ],
    benefits: [
      "2 free general practitioner consults per year with Maple",
      "Road Trip Accident Assistance<sup>5</sup>",
      "—",
      "—",
    ],
  },
  {
    cardName: "Premier",
    cardValue: 149,
    cardImg:
      "https://www.caasco.com/~/media/caasco/membership/cards/membership_card_Premier.png",
    cardLink: {
      url: "https://www.caasco.com/membership/Join?Type=Basic",
      label: "Join Now",
    },
    selectValue: "premier",
    bestValue: false,
    rvOption:"RV option for $62/year more",
    roadside: [
      "Five service calls",
      "Towing distance of 320 km on one call and 200 km on four calls<sup>1</sup>",
      "Free emergency fuel and delivery.",
      "Mobile battery service<sup>2</sup>",
      "Member pricing on CAA Premium Battery purchase plus 20 CAA Dollars<sup>&reg;</sup><sup>2</sup>",
      "CAA Bike Assist<sup>&trade;</sup><sup>3</sup>",
      "Car, bike and motorcycle coverage",
    ],
    savings: [
      "Free Canadian passport photos",
      "Additional 10% off Member pricing on merchandise online with shopwithcaa.com and in CAA Stores<sup>4</sup>",
      "Save instantly at any of the 124,000 participating retail locations in North America. You can save on apparel, restaurants, the latest tech, entertainment and more",
      "Save or get perks on travel, including car rentals, hotel stays, vacation packages and more",
    ],
    benefits: [
      "2 free general practitioner consults per year with Maple",
      "Road Trip Accident Assistance<sup>5</sup>",
      "Road Trip Interruption Assistance⁶",
      "Vehicle return benefit",
    ],
  },
];
